import SideBar from '@/components/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ChatGPT Clone App',
  description: 'Generated by create next app and deji ice',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
          {/* sidebar */}
          <SideBar/>
          {/* client provifer -- chatgpt notfication */}
          
          <div className='bg-[#343541] flex-1'>
          {children}
          </div>
          </div>
        </body>
    </html>
  )
}
